# Site settings
title: Benoit Zhong
description: Software Engineering Student
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zhong.fr" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Benoit Zhong
user_description: Software Engineering Student
user_title: Software Engineering Student
#email: anon@anon.com
twitter_username: zhongueries
github_username:  BScong
instagram_username: benoitzhong
linkedin_username: benoit-zhong
medium_username: benoit.zhong
#facebook_username: Benoit.Zhong
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-110557429-1"

exclude: ['package.json', 'src' , 'node_modules']
